### ISSUE TITLE
Helm Chart : Versions of dependencies unavailable

### ISSUE THREAD

**Issue by B3nBeng** [zulip/docker-zulip#383] opened 2023-01-27 16:34 UTC
Hi,

The versions specified (in Chart.yaml) of redis, memcached, rabbitmq and postgresql are not available anymore on Bitnami repo.

"Error: can't get a valid version for repositories memcached, rabbitmq, redis, postgresql. Try changing the version constraint in Chart.yaml"

**Comment by alexmv** [comment] 2023-02-16 16:08
It looks like Bitnami dropped old releases from their index: bitnami/charts#10539.

We can either move to their GitHub-hosted archive:
```diff
diff --git kubernetes/chart/zulip/Chart.yaml kubernetes/chart/zulip/Chart.yaml
index b25b7bb..19f9d0f 100644
--- kubernetes/chart/zulip/Chart.yaml
+++ kubernetes/chart/zulip/Chart.yaml
@@ -15,22 +15,22 @@ version: 0.4.0
 appVersion: "6.1-0"
 dependencies:
   - name: memcached
-    repository: https://charts.bitnami.com/bitnami
+    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
     tags:
       - memcached
     version: 6.0.16
   - name: rabbitmq
-    repository: https://charts.bitnami.com/bitnami
+    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
     tags:
       - rabbitmq
     version: 8.32.0
   - name: redis
-    repository: https://charts.bitnami.com/bitnami
+    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
     tags:
       - redis
     version: 16.8.7
   - name: postgresql
-    repository: https://charts.bitnami.com/bitnami
+    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
     tags:
       - postgresql
     # Note: values.yaml overwrites posgresql image to zulip/zulip-postgresql:14
```
or, we can update the chart to the latest versions:
```diff
diff --git kubernetes/chart/zulip/Chart.yaml kubernetes/chart/zulip/Chart.yaml
index b25b7bb..79bad77 100644
--- kubernetes/chart/zulip/Chart.yaml
+++ kubernetes/chart/zulip/Chart.yaml
@@ -18,23 +18,23 @@ dependencies:
     repository: https://charts.bitnami.com/bitnami
     tags:
       - memcached
-    version: 6.0.16
+    version: 6.3.5
   - name: rabbitmq
     repository: https://charts.bitnami.com/bitnami
     tags:
       - rabbitmq
-    version: 8.32.0
+    version: 11.9.1
   - name: redis
     repository: https://charts.bitnami.com/bitnami
     tags:
       - redis
-    version: 16.8.7
+    version: 17.7.4
   - name: postgresql
     repository: https://charts.bitnami.com/bitnami
     tags:
       - postgresql
     # Note: values.yaml overwrites posgresql image to zulip/zulip-postgresql:14
-    version: 11.1.22
+    version: 11.9.13

 sources:
   - https://github.com/zulip/zulip
```

Can you try the latter and let us know if it works for you?

**Comment by B3nBeng** [comment] 2023-02-21 14:11
Thanks you for the link of archives.
For the latest versions, it's works, i updated the Chart.yaml before opening this issue but i had few bugs with RabbitMQ so i wanted to try with the same versions specifies in the origin Chart.yaml but the version is not the problem.

**Comment by alexmv** [comment] 2023-02-28 20:22
If the new versions work, we should bump our dependencies to them so we fix this for others.

**Comment by AdamJSoftware** [comment] 2024-05-29 11:35
How did you end up fixing the rabbitmq issues?

**Comment by timabbott** [comment] 2024-09-26 00:12
I've definitely seen issues in the past with Docker/Kubernetes environments killing network connections that have been alive for more than 60 seconds or some other fixed period; that is likely the cause of the errors you're seeing in logs.

The Helm chart versions have been updated, so closing this issue as fixed.

**Closed by timabbott** 2024-09-26 00:12 UTC
