### ISSUE TITLE
Version 9.0 and 9.1 "ZulipLDAPAuthBackend" Issue with TLS on ldaps 636

### ISSUE THREAD

**Issue by deadRabbit92** [zulip/docker-zulip#454] opened 2024-08-07 06:10 UTC
Hello,

we are running zulip docker for about a year now, starting from Version 7 and really enjoying the product! Good work!

Now that we upgraded our "dev" machine to version 9.0 to test the upgrade we are facing issues with authenticating through ldap. In the logs we just see:

`ldap.SERVER_DOWN: {'result': -1, 'desc': "Can't contact LDAP server", 'ctrls': [], 'info': '(unknown error code)'}`

also we found out that if you add 

`echo 'TLS_REQCERT allow' >> /etc/ldap/ldap.conf`

inside the zulip docker container, it works again. But we don't want to ignore certificate checks for ldap tls. 
We use a official publicly trusted certificate on ldaps which is bought from GoDaddy, which properly verifys when using openssl command even from inside the zulip docker cli. We also tried version 9.1 but it is the same result.

Please help us :) 
Thank you!

BR,
Felix

**Comment by sgabenov** [comment] 2024-08-12 15:05
We are facing the same issue. How do we can add a SSL certificate to avoid such behavior?
Also would be nice, if LOGS will be more informative over this issue

**Comment by mhassouna95** [comment] 2024-08-19 15:13
Facing the same issue, would be nice to have a fix for this

**Comment by deadRabbit92** [comment] 2024-09-03 07:29
Hi,

can we get an update on this? Please :)

BR,
Felix

**Comment by eleanoremeyer** [comment] 2024-09-09 21:01
Hello,

we were facing the same issue.
As a workaround, it helped to add the following two lines to `Dockerfile` in order to point :

```
RUN mkdir /etc/ldap && \
    echo 'TLS_CACERTDIR /etc/ssl/certs' >> /etc/ldap/ldap.conf
```

This is maybe a bit more sensible than to just accept all certificates.
(And then of course you have to rebuild & restart the container)

**Comment by ivanbakel** [comment] 2024-10-25 17:37
Also encountered this issue, which broke a previously-working setup on upgrade since both LDAP+STARTTLS and LDAPS stopped working.

[This issue from another Docker repo](https://github.com/netbox-community/netbox-docker/issues/799) suggests that installing `libldap-common` in the Dockerfile is a sufficient fix. I'm going to test this myself (though it's very painful to rebuild the image.)

**Comment by timabbott** [comment] 2024-11-08 19:17
Folks, [chat.zulip.org](https://zulip.com/development-community/) is the best place to get help with issues setting up a server. 

@ivanbakel did your test determine that installing `libldap-common` fixed this issue for you? If so, that seems like an easy tweak to the `Dockerfile` that we could include in 9.3.

**Comment by ivanbakel** [comment] 2024-11-14 22:33
I can confirm that installing `libldap-common` leads to the `/etc/ldap/ldap.conf` file being present with the desired cert settings on the image, and this fixes the LDAP issue.

**Comment by timabbott** [comment] 2024-11-14 23:14
It looks like the reason this hasn't come up outside Docker is that a postgres database ends up pulling this in:
```
$ aptitude why libldap-common
i   postgresql-16 Depends    libldap-2.5-0 (>= 2.5.4)
i A libldap-2.5-0 Recommends libldap-common          
```

**Closed** 2024-11-15 23:08 UTC
Labels: high priority
