### ISSUE TITLE
Cannot set custom SSL certs or settings

### ISSUE THREAD

**Issue by alexamirante** [zulip/docker-zulip#387] opened 2023-02-16 15:32 UTC
Commit 74aea021cecffc11fdb9690b6859748019bd04e0 broke the possibility of providing custom SSL certs or `settings.py` as explained in the README [here](https://github.com/zulip/docker-zulip/blob/main/README.md?plain=1#L188-L191) and [here](https://github.com/zulip/docker-zulip/blob/main/README.md?plain=1#L210-L213).

A workaround is to first start the container, then inspect where the docker volume files are stored on the file system via `docker volume inspect docker-zulip_zulip`, and finally put the files there. But this wouldn't work if you don't have root privileges on the machine.

**Comment by timabbott** [comment] 2024-11-08 19:07
The nature of the breakage wasn't specified in this report, but I think this is probably effectively a duplicate of #343 -- that with named volumes, it's harder to predict the paths to use.

**Closed by timabbott** 2024-11-08 19:07 UTC
