### ISSUE TITLE
Do not receive a message with login and password

### ISSUE THREAD

**Issue by zivarg** [zulip/docker-zulip#126] opened 2018-06-23 08:14 UTC
I installed everything as written in the documents. I understand that in order to get the password after the first launch of the docker, it should be sent to the specified name in the settings? So I'm doing my login, and nothing arrives at the post office, although the send_test_email from the container is working and the messages are coming. How to solve my problem? The connection is via Port 465, SSL: True, TLS: False.

**Comment by timabbott** [comment] 2018-06-23 19:06
@zivarg if `send_test_email` is working and other emails are not I suspect the issue is the second bullet here: http://zulip.readthedocs.io/en/latest/production/email.html#troubleshooting

(Basically, that we send from a noreply email).  Can you investigate that?  Otherwise, check `/var/log/zulip/errors.log`.

(The fact that `send_test_email` doesn't throw an error with that misconfiguration is a bug fixed in master)

**Comment by zivarg** [comment] 2018-06-23 19:51
All that is described in the documentation is completed, two letters come to the mail, but the system on Forgot password, Register, does not respond to these events, even in the logs there is no information.

**Comment by zivarg** [comment] 2018-06-23 20:02
Are you sure that when you start the docker, the user's entry into the database, because when I press the registration, or forgot the password, the system translates to the search tab of the user search and password recovery for it?

**Comment by zivarg** [comment] 2018-06-23 22:52
I'm also trying to figure out in my own right what the reason for this work is zulip through the docker, since it works correctly through the installer without the docker. I noticed that you have two /etc/zulip/settings.py the settings file.

**Comment by gioragutt** [comment] 2018-07-08 14:15
Hi @zivarg, if you're talking about the case where even with correct credentials, you cannot login - seek to upgrade the browser. When my users failed to login, upgrading the browser from (chrome/chromium) from 43 to even 50, fixed the issue.

**Comment by julien-tmp** [comment] 2019-08-04 20:03
Hi @zivarg . You probably missed he organization setup.
If you have not found the link in the logs, you can exec -ti in your container and use
`su zulip -c '/home/zulip/deployments/current/manage.py generate_realm_creation_link'`

**Comment by timabbott** [comment] 2024-09-26 00:46
We've reworked how organization creation works since this issue was opened, and in particular it's now a web flow that avoids this whole class of failure mode. Belated thanks for the reports and investigation folks!

**Closed by timabbott** 2024-09-26 00:46 UTC
