### ISSUE TITLE
Settings.py or environment Variables

### ISSUE THREAD

**Issue by aiveras** [zulip/docker-zulip#242] opened 2020-02-16 19:05 UTC
Since the new update LDAP no longer works directly. Unfortunately I didn't find anything about this in the documentation:
Shouldn't settings be set with environment variables? Or in settings.py?
It is also not clear if SAML can be set with the environment variables.

**Comment by timabbott** [comment] 2020-03-05 01:58
I don't believe we have a way for SAML to work with environment variables.  We recommend using MANUAL_CONFIGURATION with a `settings.py` file for that.

What issue do you get with LDAP done via environment?  In general environment variables are not a super robust way to pass the relatively complex parameters involved in LDAP, so I'm not sure it's possible to make that work in all cases.

But it sounds like you think there's a regression, and if it is, we should fix it.

**Comment by magesh1983** [comment] 2020-04-18 11:09
Me too go into an issue when setting up LDAP authentication inside docker-zulip.  Based upon little debugging found the following thing. Looks like entrypoint.sh: authenticationBackends() is not able to parse the ZULIP_AUTH_BACKENDS properly.  It always sets only EmailAuthBackend irrespective of what is given in ZULIP_AUTH_BACKENDS.   By the way I am able to get it work successfully using ZULIP_CUSTOM_SETTINGS: "AUTHENTICATION_BACKENDS = `('zproject.backends.EmailAuthBackend','zproject.backends.ZulipLDAPAuthBackend',)"`

**Comment by Alexandre-Silva** [comment] 2024-02-04 16:14
Hello,

Just letting you know that as of this writting, ZULIP_CUSTOM_SETTINGS works for me

**Comment by timabbott** [comment] 2024-09-26 00:50
Yeah, agreed, closing this as fixed through the array-format settings support we added a few years back.

**Closed by timabbott** 2024-09-26 00:50 UTC
